name: Wakatime Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Atualiza todo dia à meia-noite
  workflow_dispatch:  # Permite executar manualmente

jobs:
  update-readme:
    name: Update README with WakaTime stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Update README
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_TITLE: true
          SHOW_TOTAL_CODE_TIME: true
          SHOW_PROFILE_VIEWS: false
          SHOW_COMMIT: true
          SHOW_DAYS_OF_WEEK: true
          SHOW_LANGUAGE: true
          SHOW_OS: true
          SHOW_PROJECTS: true
          SHOW_TIMEZONE: true
          SHOW_EDITORS: true
          SHOW_LANGUAGE_PER_REPO: true
          SHOW_SHORT_INFO: false
          SHOW_LOC_CHART: false
